### ISSUE TITLE
Code check-in ETA

### ISSUE THREAD

**Issue by lweberk** [cruisercoder/cppstddb#1]
Hi,

saw the talk at cppcon16 on youtube. Just wondering how the lib was coming along?

Would be a terrifically nice thing to play around with and eventually work with. 
Currently maintaining a roughly similar approach –without the separation between API and driver– for a pgsql library internally. Maybe there is something I can do to help on the pgsql driver implementation side? 

Best Regards,
~lweberk

**Comment by cruisercoder** [comment]
Hi iweberk - thanks for the interest!  Sorry for delay, I just got a bit swamped after the conference, but initial check-in coming soon - probably this week and want to make some sustained progress on it to get it to a stable state.  It would be great to get some help with the pgsql driver.  I'll likely have some implementation of a pgsql driver present but as with all the drivers, there will be missing capabilities (particularly with binding for all types).  Check back this week.

**Comment by lweberk** [comment]
Great Will do. Thank you.

**Comment by Ali-Se** [comment]
Me too!
Waiting for ETA.

**Comment by qicosmos** [comment]
Token.

**Comment by blastmaster** [comment]
I'am also looking forward to see some code I can play with. At the moment I'am very frustrated when trying to use C++ with databases. Also I had some resources to maybe contribute, especially for NoSQL Databases, which mostly rely on REST APIs.

**Comment by lweberk** [comment]
Allow me to follow-up with a sign of life ^^. How is it coming?

**Comment by Ali-Se** [comment]
I think I can help in adding SQL Server interface.

**Comment by madmongo1** [comment]
Saw the talk. I have an interest in using this now (otherwise will continue with my own). Happy to contribute. Can probably offer some guidance on dynamic variadic args and non-blocking.

**Comment by cruisercoder** [comment]
new for 2017: actual code!  Very rough code to start but I'm going to try to produce a steady stream of commits.

**Comment by lweberk** [comment]
Excellent! Many thanks! and happy new year!
