### ISSUE TITLE
Add licence to project

### ISSUE THREAD

**Issue by lweberk** [cruisercoder/cppstddb#11]
To clarify conditions.

**Comment by lweberk** [comment]
Would be lovely to have an Idea about this one as soon as humanly possible. Without a licence it becomes really hard to justify contribution.

**Comment by cruisercoder** [comment]
Hi Leonhard.  Sorry for the delay on this.  I'm very happy that you are
interested and I see if I can start to get back to working on this project
today.  I'll take care of the license ASAP.

erik

**Comment by blastmaster** [comment]
I'am agree with @lweberk with a license file it's possible to start contributions. What kind of license do you want to take? Other C++ libraries often use the boost-license. I think that could be a reasonable choice.

**Comment by cruisercoder** [comment]
BSL-1.0 license added to project. More to come soon...
